### ISSUE TITLE
ps_datetime_to_season()

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poisix#1]
Function to separate DateTime or Date into 4 seasons?
ability to set season start/end times but with useful defaults

**Comment by joethorley** [comment]
I think this would be useful.

Thoughts - Jan-Mar (spring) April-Jun (summer) July-Sep (autumn) October-December (winter) is a possible default?

**Comment by sebdalgarno** [comment]
I wonder if everything should be pushed forward a couple months: March-May (Spring), June-August (summer), September-November (Autumn), December-February (Winter). Is your suggested default something you've used in the past, or something that is standard for these kinds of studies? The benefit of yours is that no season straddles two years.

**Comment by joethorley** [comment]
I think yours is more accurate. There should also be a way to get the year
ie Dec 2016-Feb 2017 is really winter 2016. One option is to take a
dataframe and a col specifying the date (or date time to use) and to return
the original data frame with two new cols Season and SeasonYear. This also
has the advantage that we could in the future extend to take a spatial
column as well to use when determining the season. Thoughts?

Sent from my iPhone

On Jan 13, 2018, at 00:35, Seb Dalgarno <notifications@github.com> wrote:

I wonder if everything should be pushed forward a couple months: March-May
(Spring), June-August (summer), September-November (Autumn),
December-February (Winter). Is your suggested default something you've used
in the past, or something that is standard for these kinds of studies? The
benefit of yours is that no season straddles two years.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/poissonconsulting/poisix/issues/1#issuecomment-357418926>,
or mute the thread

**Comment by sebdalgarno** [comment]
NOAA definition of meteorological seasons seems like a good default:
https://www.ncdc.noaa.gov/news/meteorological-versus-astronomical-summer—what’s-difference

It is the same as suggested in my above comment, so let's go with that...
Adding a SeasonYear is a good idea.

What is your stance on returning a tibble vs. a vector? In this case the need for SeasonYear necessitates returning a tibble, although I'm not sure that that's ideal.
I like returning a vector as it can be used within a mutate call:
`df %<>% mutate(Season = ps_get_season(DateTime))`

**Comment by joethorley** [comment]
I agree.

The tibble versus vector question is a good one. If we just needed to know the season then I would say return a vector but because we need the season and the season year I think it should return a tibble.

The mutate advantage is big however achieve this by making it return the original data frame plus the Season and SeasonYear column so it can be used in pipes with the user able to override the default names for season and season_year.

A third alternative is to have vector returning functions for season and season year and a tibble returning function that does both ie `ps_get_season` and `ps_get_season_year` and `ps_add_season_year`

```
ps_add_season <- function(x, date = "Date", season = "Season", season_year = "SeasonYear") {
 ...
  x[[season]] <- ps_get_season(x[[date]])  
  x[[season_year]] <- ps_get_season_year(x[[date]])
x
}
```
 
I think it should work on dates by default and use the lubridate::date function to convert date times to date automatically.

**Comment by sebdalgarno** [comment]
I like the third alternative...only disadvantage is that if we start doing it a lot it will lead to a huge number of functions to wade through. However, I think situations in which two columns need to be output will be limited.

Going forward, should we try and stick with that grammar? i.e. 'get' means vector output and 'add' means tibble output.

**Comment by joethorley** [comment]
yes I think stick with that grammar

**Comment by sebdalgarno** [comment]
having a bit of trouble understanding how season_year is calculated. Might be easier for you to simply finish the function if it is clear in your mind:

here is ps_get_season:
```
ps_get_season <- function(x, winter = c(12L, 1L, 2L), spring = c(3L, 4L, 5L),
                          summer = c(6L, 7L, 8L), autumn = c(9L, 10L, 11L)){

  if(!is_dt(x)) ps_error("x must be a Date or POSIXct object.")
  if(!is_monthL(winter)) poisutils::ps_error("winter must contain integers from 1 to 12")
  if(!is_monthL(spring)) poisutils::ps_error("spring must contain integers from 1 to 12")
  if(!is_monthL(summer)) poisutils::ps_error("summer must contain integers from 1 to 12")
  if(!is_monthL(autumn)) poisutils::ps_error("autumn must contain integers from 1 to 12")

  x %<>% as.Date() %>%
    lubridate::month()

  x[x %in% winter] <- "Winter"
  x[x %in% spring] <- "Spring"
  x[x %in% summer] <- "Summer"
  x[x %in% autumn] <- "Autumn"

  x %<>% factor(levels = c("Winter", "Spring", "Summer", "Autumn"))
  x
}
```

**Comment by joethorley** [comment]
I made a few tweaks to `ps_get_season()` to make it more flexible and quicker to specify the seasons and so that it also returns an ordered factor and I added `ps_add_season()` which adds a season and year column. I didn't bother with `ps_get_year_season()` is it is only really useful when combined with the season. Please review and let me know if you have any comments/suggestions.

**Comment by sebdalgarno** [comment]
awesome. Learned a lot looking at that code as many functions would not have used...also a nice reminder on how useful check_vector  and checkor is.

on line 42 should it be `lubridate::date()` instead of `date()` which is a base function, and which I don't think works in this case?

only small suggestion is to change the default `year` arg to "SeasonYear" (and perhaps the arg name to season_year) so as not to confuse it with something generated simply by lubridate::year.

**Comment by sebdalgarno** [comment]
also if `ps_add_season()` inherits params from `ps_get_season()` does the:
```
 seasons = list(Spring = 3L, Summer = 6L,
                          Autumn = 9L, Winter = 12L)
```
still need to be there?

**Comment by joethorley** [comment]
`lubridate::date()` is not necessary because in namespace.R `#' @import lubridate` which means `base::date()` is masked however for readability I added it

good suggestion - I went with `year_season = "YearSeason"`

`#' @inheritParams ps_get_season` only inherits the documentation for shared parameters not the default values

**Comment by joethorley** [comment]
also I changed the functions so that `seasons = c(Spring = 3L, Summer = 6L, Autumn = 9L, Winter = 12L)`, ie seasons takes a named integer vector as opposed to a named list

**Comment by sebdalgarno** [comment]
great thanks for clarification re: namespace.R `#' @import lubridate` and `@inheritParams`
